[versions]
# plugins
shadow = "9.3.0"
gradle-plugins = "1.6.0"

[libraries]

shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[plugins]

mavenCentralPortal = { id = "dev.siroshun.gradle.plugins.maven-central-portal", version.ref = "gradle-plugins" }
